# just a weird code generation bug on 2006-04-08 (uncaught exception)
class Test

	def run
		print Exception('[.getType()]')

	shared
		def main
			Test().run()
